"""initial_schema

Revision ID: b1ffa32f19bf
Revises: 
Create Date: 2026-10-03 22:08:48.999818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ffa32f19bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('tahun_akademik', sa.String(length=50), nullable=False),
    sa.Column('bukti_fisik', sa.String(length=50), nullable=False),
    sa.Column('original_file_name', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('parser_engine', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('khp_jabatan_prestasi',
    sa.Column('id_jabatan_prestasi', sa.Integer(), nullable=False),
    sa.Column('nm_jabatan_prestasi', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_jabatan_prestasi')
    )
    op.create_table('khp_kelompok_kegiatan',
    sa.Column('id_kelompok_kegiatan', sa.Integer(), nullable=False),
    sa.Column('nm_kelompok_kegiatan', sa.Text(), nullable=False),
    sa.Column('is_aktif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_kelompok_kegiatan')
    )
    op.create_table('khp_tingkat',
    sa.Column('id_tingkat', sa.Integer(), nullable=False),
    sa.Column('nm_tingkat', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_tingkat')
    )
    op.create_table('extracted_fields',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('form_field_name', sa.String(length=120), nullable=False),
    sa.Column('extracted_value', sa.Text(), nullable=True),
    sa.Column('mapped_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_fields_document_id'), 'extracted_fields', ['document_id'], unique=False)
    op.create_table('extraction_jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('temp_file_key', sa.String(length=64), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_jobs_document_id'), 'extraction_jobs', ['document_id'], unique=False)
    op.create_index('ix_extraction_jobs_lease', 'extraction_jobs', ['status', 'lease_expires_at'], unique=False)
    op.create_index('ix_extraction_jobs_polling', 'extraction_jobs', ['status', 'available_at', 'created_at'], unique=False)
    op.create_table('khp_kegiatan_1',
    sa.Column('id_kegiatan_1', sa.Integer(), nullable=False),
    sa.Column('nm_kegiatan_1', sa.Text(), nullable=False),
    sa.Column('id_kelompok_kegiatan', sa.Integer(), nullable=False),
    sa.Column('is_aktif', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_kelompok_kegiatan'], ['khp_kelompok_kegiatan.id_kelompok_kegiatan'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_kegiatan_1')
    )
    op.create_table('khp_master_resolutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('resolution_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('khp_kegiatan_2',
    sa.Column('id_kegiatan_2', sa.Integer(), nullable=False),
    sa.Column('id_kegiatan_1', sa.Integer(), nullable=False),
    sa.Column('id_tingkat', sa.Integer(), nullable=True),
    sa.Column('id_jabatan_prestasi', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_jabatan_prestasi'], ['khp_jabatan_prestasi.id_jabatan_prestasi'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_kegiatan_1'], ['khp_kegiatan_1.id_kegiatan_1'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_tingkat'], ['khp_tingkat.id_tingkat'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_kegiatan_2')
    )
    op.create_table('khp_master_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_no', sa.Integer(), nullable=False),
    sa.Column('id_kelompok_kegiatan', sa.Integer(), nullable=False),
    sa.Column('id_kegiatan_1', sa.Integer(), nullable=False),
    sa.Column('id_tingkat', sa.Integer(), nullable=True),
    sa.Column('id_jabatan_prestasi', sa.Integer(), nullable=True),
    sa.Column('dasar_penilaian', sa.Text(), nullable=False),
    sa.Column('id_kegiatan_2', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['id_jabatan_prestasi'], ['khp_jabatan_prestasi.id_jabatan_prestasi'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_kegiatan_1'], ['khp_kegiatan_1.id_kegiatan_1'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_kegiatan_2'], ['khp_kegiatan_2.id_kegiatan_2'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_kelompok_kegiatan'], ['khp_kelompok_kegiatan.id_kelompok_kegiatan'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_tingkat'], ['khp_tingkat.id_tingkat'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('khp_master_rules')
    op.drop_table('khp_kegiatan_2')
    op.drop_table('khp_master_resolutions')
    op.drop_table('khp_kegiatan_1')
    op.drop_index('ix_extraction_jobs_polling', table_name='extraction_jobs')
    op.drop_index('ix_extraction_jobs_lease', table_name='extraction_jobs')
    op.drop_index(op.f('ix_extraction_jobs_document_id'), table_name='extraction_jobs')
    op.drop_table('extraction_jobs')
    op.drop_index(op.f('ix_extracted_fields_document_id'), table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_table('khp_tingkat')
    op.drop_table('khp_kelompok_kegiatan')
    op.drop_table('khp_jabatan_prestasi')
    op.drop_table('documents')
    # ### end Alembic commands ###
